"use client";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { usePathname } from "next/navigation";
import Navbar from "@/components/navbar-landing"; // Ganti dengan navbar yang kamu mau

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const pathname = usePathname();

  // Daftar path yang TIDAK butuh navbar
  const noNavbarPaths = ["/"];

  const shouldShowNavbar = !noNavbarPaths.includes(pathname);

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {shouldShowNavbar && <Navbar />}
        {children}
      </body>
    </html>
  );
}
